import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { JSONLD } from '@/components/JSONLD';
import { Analytics } from '@vercel/analytics/next';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-full min-h-screen flex flex-col`}>
        {children}

        <JSONLD
          data={{
            '@context': 'https://schema.org',
            '@type': 'Organization',
            name: 'KATTCORP',
            legalName: 'KATTCORP AB',
            url: 'http://kattcorp.com',
            foundingDate: '2016-10-26',
            founders: [
              {
                '@type': 'Person',
                name: 'Alexander Johansson',
              },
            ],
            address: {
              '@type': 'PostalAddress',
              addressCountry: 'Sweden',
            },
            contactPoint: {
              '@type': 'ContactPoint',
              contactType: 'sales',
              email: 'alex@kattcorp.com',
              url: 'https://twitter.com/alexdotjs',
            },
            sameAs: [
              'https://github.com/KATT',
              'https://www.linkedin.com/in/johanssonalexander/',
              'https://www.linkedin.com/company/19376256/',
              'https://twitter.com/alexdotjs',
              'https://katt.dev',
              'https://kattcorp.com',
              'https://kattcorp.co.uk',
            ],
          }}
        />
        <Analytics />
      </body>
    </html>
  );
}
